### ISSUE TITLE
Decide on recipes

### ISSUE THREAD

**Issue by BachChiu** [Quan987/webdev-pro-team2#5]

**Comment by CookieStudios5609** [comment]
I think one of them should be something you bake. 

1. Easy animations (just wiggle a spoon in the bowl, just turn the oven's window red, just scale up the top of the baked good, etc)
2. Everyone likes baked goods
3. Animating the ingredients list is just as simple as the instructions

**Comment by CookieStudios5609** [comment]
Resolved and closed with 50403d30dadb816d4cd9b7c9fe597059550b82c2
